### ISSUE TITLE
Ensure we have e2e test coverage

### ISSUE THREAD

**Issue by richardcase** [rancher-sandbox/rancher-turtles#15] opened 2023-06-19 11:50 UTC
**Story**

As a rancher turtles dev,
I want to have e2e test coverage,
So that i have confidence that there are no regressions.

**Description**
We need a way to test e2e scenarios of the operator.

**Comment by alexander-demicev** [comment] 2023-07-26 15:58
duplicate of https://github.com/rancher-sandbox/rancher-turtles/issues/46

**Closed by alexander-demicev** 2023-07-26 15:58 UTC
